name: brain_app
description: Brain Hausaufgaben Heft App

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  table_calendar: ^3.0.6
  flutter_rounded_date_picker: 2.0.2
  shared_preferences: ^2.0.15
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter
  drift: ^1.4.0
  localstorage: ^4.0.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.0
  path: 1.8.0
  flutter_colorpicker: ^1.0.3
  flutter_speed_dial: ^6.0.0
  url_launcher: ^6.1.3
  flutter_local_notifications: ^9.0.0
  package_info_plus: ^1.0.6
  flutter_device_type: ^0.4.0
  cupertino_icons: ^1.0.2
  csv: ^5.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  drift_dev: ^1.4.0
  build_runner: ^2.1.7
  flutter_launcher_icons: ^0.9.0

  flutter_lints: ^1.0.0


flutter_icons:
  image_path: "icons/appIcon.jpg"
  android: "launcher_icon"
  adaptive_icon_foreground: "icons/launcherForeground.png"
  adaptive_icon_background: "icons/launcherBackground.png"

flutter:
  uses-material-design: true

  assets:
    - icons/
    - data/

  fonts:
   - family: Nunito
     fonts:
       - asset: fonts/Nunito/Nunito-ExtraBold.ttf
         weight: 800
       - asset: fonts/Nunito/Nunito-Bold.ttf
         weight: 700
       - asset: fonts/Nunito/Nunito-SemiBold.ttf
         weight: 600
       - asset: fonts/Nunito/Nunito-Medium.ttf
         weight: 500
       - asset: fonts/Nunito/Nunito-Regular.ttf
         weight: 400
