name: brain_app
description: Brain Hausaufgaben Heft App
publish_to: 'none'
version: 0.2.0

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter_svg: ^1.0.0
  table_calendar: ^3.0.6
  flutter_rounded_date_picker: 2.0.2
  flutter_scroll_shadow: ^1.0.2
  shared_preferences: ^2.0.15
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter
  drift: ^1.4.0
  localstorage: ^4.0.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.0
  path: 1.8.0
  flutter_colorpicker: ^1.0.3
  flutter_speed_dial: ^6.0.0
  url_launcher: ^6.1.3
  flutter_local_notifications: ^9.0.0
  package_info_plus: ^1.0.6
  flutter_device_type: ^0.4.0
  cupertino_icons: ^1.0.2
  http: ^0.13.4
  dio: ^4.0.6
  dynamic_color: ^1.0.0
  quick_actions: ^0.6.0+11
  csv: ^5.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  drift_dev: ^1.4.0
  build_runner: ^2.1.7
  flutter_launcher_icons: ^0.9.0

  flutter_lints: ^1.0.0


flutter_icons:
  image_path: "icons/appIcon.jpg"
  android: "launcher_icon"
  adaptive_icon_foreground: "icons/launcherForeground.png"
  adaptive_icon_background: "icons/launcherBackground.png"

flutter:
  uses-material-design: true

  assets:
    - icons/
    - data/

  fonts:
   - family: Nunito
     fonts:
       - asset: fonts/Nunito/Nunito-ExtraBold.ttf
         weight: 800
       - asset: fonts/Nunito/Nunito-Bold.ttf
         weight: 700
       - asset: fonts/Nunito/Nunito-SemiBold.ttf
         weight: 600
       - asset: fonts/Nunito/Nunito-Medium.ttf
         weight: 500
       - asset: fonts/Nunito/Nunito-Regular.ttf
         weight: 400
