name: brain_app
description: Brain Hausaufgaben Heft App
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  sticky_headers: ^0.3.0
  numberpicker: ^2.0.1
  flutter_svg: ^1.0.0
  table_calendar: ^3.0.6
  flutter_rounded_date_picker: ^3.0.1
  flutter_scroll_shadow: ^1.0.2
  shared_preferences: ^2.0.15
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter
  localstorage: ^4.0.0
  path_provider: ^2.0.0
  path: ^1.8.1
  flutter_colorpicker: ^1.0.3
  flutter_speed_dial: ^6.0.0
  url_launcher: ^6.1.3
  flutter_local_notifications: ^9.0.0
  package_info_plus: ^1.0.6
  flutter_device_type: ^0.4.0
  http: ^0.13.4
  dio: ^4.0.6
  quick_actions: ^0.6.0+11
  csv: ^5.0.1
  audioplayers: ^1.0.1
  flutter_staggered_animations: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.7
  flutter_launcher_icons: ^0.9.0
  flutter_lints: ^1.0.0


flutter_icons:
  image_path: "icons/appIcon.jpg"
  android: "launcher_icon"
  adaptive_icon_foreground: "icons/launcherForeground.png"
  adaptive_icon_background: "icons/launcherBackground.png"

flutter:
  uses-material-design: true

  assets:
    - icons/
    - data/
    - images/

  fonts:
   - family: Inter
     fonts:
       - asset: fonts/Inter/Inter-ExtraBold.ttf
         weight: 800
       - asset: fonts/Inter/Inter-Bold.ttf
         weight: 700
       - asset: fonts/Inter/Inter-SemiBold.ttf
         weight: 600
       - asset: fonts/Inter/Inter-Medium.ttf
         weight: 500
       - asset: fonts/Inter/Inter-Regular.ttf
         weight: 400
